### PR TITLE
fix(icons): match new Nerd Fonts 3.0.0 release

### PR DESCRIPTION
**Pull request by XenoPhex**
See the following links for more information:
- https://github.com/ryanoasis/nerd-fonts/issues/365
- https://github.com/ryanoasis/nerd-fonts/issues/1059#issuecomment-1404891287

### CODE REVIEW

**Comment by mhanberg** [comment]
This branches fixes the broken icons for me. My JetBrainsMonoNerdFonts updated the other day and they've been broken ever since.

**Comment by XenoPhex** [comment]
For those looking for a fuller list of icons that popular tools are using, feel free to use mine - I updated it recently to finish the 3.0.0 release: https://github.com/XenoPhex/nvim/blob/42192ef0c637c3ae6e274df4b7b2df633577a72c/lua/utils/icons.lua#L43-L160

**Comment by SmiteshP** [comment]
Is it just me or are these newer replacement icons very tiny in comparison to older ones?

**Comment by tylerw** [comment]
Using this branch, the replacements seem normal sized to me:
Screen Shot 2023-05-08 at 1 50 33 PM

Using kitty v0.28.1, FiraCode Nerd Font Mono Retina (Nerd font v3.0.0), Neovim v0.10.0-dev-295+g01f81ed89.

**Review by SmiteshP — APPROVED** [review]
LGTM Thanks! :)

**Pull request merged**
