### PR TITLE
Fix: Lualine example error

### PR DESCRIPTION
**Pull request by karma-riuk**
Fix for #121

### CODE REVIEW

**Comment by SmiteshP** [comment]
Thanks for pointing this out! 
Can you add this fix for the winbar part as well? line 291 to 293

**Comment by karma-riuk** [comment]
Done :)

**Review by SmiteshP — APPROVED** [review]
Thanks a lot

**Comment by SmiteshP** [comment]
idk why I forgot to merge this 🤦‍♂️

**Pull request merged**
