### PR TITLE
move curr nil check to for loop

### PR DESCRIPTION
**Pull request by ChristianChiarulli**
I have experienced curr being null on line 137, this seems to fix the issue.

### CODE REVIEW

**Comment by smjonas** [comment]
This was already fixed (see #35)

**Comment by ChristianChiarulli** [comment]
#35 fixes the entry in curr being nil, not curr itself

**Comment by smjonas** [comment]
Well, it does check `curr` but you're still right that this is not the same fix because `curr` can be set to a different value in the loop which I didn't notice ;)

**Review by SmiteshP — APPROVED** [review]
LGTM! Thanks :)

**Pull request merged**
