### PR TITLE
Execute autocommand on data update

### PR DESCRIPTION
**Pull request by shurizzle**
Execute a User NavicUpdate event with data `{ buf = <bufnr> }` when navic updates data

### CODE REVIEW

**Comment by SmiteshP** [comment]
Not sure what this will do.. Can you explain?

**Comment by shurizzle** [comment]
It generates a User event so people can listen to that event, I used it to automatically show/hide winbar for example.

https://github.com/shurizzle/neovimmizzle/blob/main/lua/config/plugins/navic.lua#L98-L104

**Comment by SmiteshP** [comment]
Looking at the code... it seems that it is just setting winbar active for a buffer if nvim-navic is available for the buffer, if not it is removing the winbar. (Am I right?)
setting or unsetting winbar can be done once at BufEnter Event also... will provide same results

**Comment by shurizzle** [comment]
Using BufEnter is not a good idea for me since language server is started before I enter the first buffer for that LS. Events can be used by everyone in many ways, not only by me in this context.

**Comment by SmiteshP** [comment]
This doesn't need to get Updated exactly when navic is getting results from LSP. This could be done with CursorMoved or CursorHold event as well if BufEnter isn't ideal 🤷🏽‍♂️

**Pull request closed without merging**
